spring:
  application:
    name: payment-kr
  data:
      mongodb:
        uri: mongodb+srv://navlag:Fg3UgAroDl8SDVDt@avsavivd.lfqko.mongodb.net/pmactoob?retryWrites=true&w=majority
server:
  port: 8090
